const ACTION_DOMAIN = 'app/Overview/Projects';

export const GET_PROJECTS_LIST = `${ACTION_DOMAIN}/GET_PROJECTS_LIST`;
export const GET_PROJECTS_LIST_SUCCESS = `${ACTION_DOMAIN}/GET_PROJECTS_LIST_SUCCESS`;
export const GET_PROJECTS_LIST_ERROR = `${ACTION_DOMAIN}/GET_PROJECTS_LIST_ERROR`;
